DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(AUTHORID BIGINT PRIMARY KEY, NAME VARCHAR(255), BIRTHDATE DATE, COUNTRY VARCHAR(255));

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(GENREID BIGINT PRIMARY KEY, NAME VARCHAR(255));

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(
  BOOKID BIGINT PRIMARY KEY,
  NAME VARCHAR(255),
  AUTHORID BIGINT REFERENCES AUTHORS(AUTHORID)
);

create table BOOKS_GENRES(
    BOOK_ID bigint references BOOKS(BOOKID) on delete cascade,
    GENRE_ID bigint references GENRES(GENREID),
    primary key (BOOK_ID, GENRE_ID)
);

