DROP TABLE IF EXISTS BOOKS_COMMENTS;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS AUTHORS;

CREATE TABLE AUTHORS(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255),
  BIRTH_DATE DATE,
  COUNTRY VARCHAR(255)
);

CREATE TABLE GENRES(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255)
);

CREATE TABLE BOOKS(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255),
  AUTHOR_ID BIGINT,
  GENRE_ID BIGINT,
  FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHORS(ID) ON DELETE CASCADE,
  FOREIGN KEY(GENRE_ID) REFERENCES GENRES(ID) ON DELETE CASCADE
);

CREATE TABLE BOOKS_COMMENTS(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255),
  AUTHOR_ID BIGINT,
  BOOK_ID BIGINT,
  FOREIGN KEY(BOOK_ID) REFERENCES BOOKS(ID) ON DELETE CASCADE,
  FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHORS(ID) ON DELETE CASCADE
);